log:
  file: 'logs/sciigo.log'
  level: DEBUG
  keep: 2
  size: 10485760
nagios:
  url: 'https://nix.eox.at/nagios3/'
  extinfo: 'https://nix.eox.at/cgi-bin/nagios3/extinfo.cgi'
pushover:
  api: 'https://api.pushover.net/1/messages.json'
  token: '1fpmgk6XBcu2lgXL6YsUHcBjLXQox4'
lox24:
  api: https://www.lox24.eu/API/httpsms.php
  konto: 1729
  password: fe360b86
  service: 1970
  from: Nagios
vars:
